events {}

http {
    server {
        listen 80;

        # 1. Все запросы по умолчанию летят на Фронтенд
        location / {
            proxy_pass http://frontend; # <-- Обращаемся по имени сервиса из docker-compose!
        }

        # 2. Запросы к API летят на Бэкенд
        # (Тебе нужно будет в Python тоже настроить, чтобы он отвечал)
        location /api/ {
            proxy_pass http://backend:8000/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}